### ISSUE TITLE
Center text

### ISSUE THREAD

**Issue by bermanapps** [EyreFree/UICountingLabel#8]
How do I center the text in the view?
Thanks

**Comment by bermanapps** [comment]
Like this: (for swift 4)
countingLabel.textAlignment = .center

**Comment by EyreFree** [comment]
@bermanapps 

If you use 'attributedFormatBlock' you can set:

```swift
let style = NSMutableParagraphStyle()
style.alignment = .center

...

let attributedText = NSMutableAttributedString (
        string: "xxxxxx", attributes: [
            NSAttributedStringKey.paragraphStyle: style
        ]
)
```

else just set 'countingLabel.textAlignment = .center' of 'EFCountingLabel'.
